### ISSUE TITLE
Android 10 Not able to open files

### ISSUE THREAD

**Issue by aditbharadwaj** [capacitor-community/file-opener#17]
**Describe the bug**
On android 10 only, i am not able to open the files it always fails to open file , as i see in log cat it says 

9.415 7372-7372/ E/Capacitor/FilesystemPlugin: Not able to create 'DOCUMENTS'!

**To Reproduce**
1. Just click on open document
2. it ask for the file permission 
3. gives error 9.415 7372-7372/ E/Capacitor/FilesystemPlugin: Not able to create 'DOCUMENTS'!

**Expected behavior**
Should be able to open the file. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6751554/198827503-3dbeb69a-ece6-4e26-a151-b83ff964f8c6.png)

**Smartphone (please complete the following information):**
 - Device: Any device with android 10
 - OS: Android
 - Version 10

**Comment by ryaa** [comment]
It seems that this is not the file opener plugin issue. The log says that the FileSystem plugin not able to create 'DOCUMENTS'. Can you please check if the suggestion from here helps - see https://forum.ionicframework.com/t/filesystem-not-able-to-create-documents-on-android-10/193902. Please also see [here](https://capacitorjs.com/docs/apis/filesystem#android)

If the above does not help, i will need a sample application (repository in the GitHub with the detailed installation/build steps) that demonstrates the issue.

**Comment by aditbharadwaj** [comment]
hi @ryaa , thanks for the quick reply , 
and yes adding android:requestLegacyExternalStorage="true" 
does solve the issue , hopefully not break on latest target sdk's.
