### ISSUE TITLE
Installation/build issue with 1.0.2

### ISSUE THREAD

**Issue by arendjantetteroo** [capacitor-community/file-opener#18]
**Describe the bug**
Installation of 1.0.2 fails due to type: "module" in package.json. 
Possibly related to the use of typescript in a nextjs project. 

**To Reproduce**
See reproducer at https://github.com/arendjantetteroo/capacitor-file-opener-bug
Steps to reproduce are in the readme

**Expected behavior**
Can be used as 1.0.1 was. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser all
 - Version 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by ryaa** [comment]
Thank you for the additional details. I confirm the problem and made the required fix - see https://github.com/capacitor-community/file-opener/pull/19. Can you please install the version of the plugin with the fix and see if it helps. To install please issue the below command:
`npm install capacitor-community/file-opener#bugfix/build-1.0.2-fails-to-install-in-nextjs-project-with-dist`

NOTE: i could successfully build and run you app with my change and the initial error is gone. However there is another one but I assume that this is not related to the file-opener plugin - see below
<img width="1680" alt="Screen Shot 2022-11-01 at 09 47 23" src="https://user-images.githubusercontent.com/3608222/199187152-b2fae187-b3ae-4024-b49c-c711a8770ec2.png">

**Comment by arendjantetteroo** [comment]
Thanks @ryaa i can confirm it now properly builds with this fix. 

The captureException error is due to sentry js missing, i just copied the smallest code to show the error. This is indeed not related and can be ignored.

**Comment by ryaa** [comment]
The fix will be included into v1.0.3
