### ISSUE TITLE
Error opening file {"code":"UNIMPLEMENTED"}

### ISSUE THREAD

**Issue by pmosedale** [capacitor-community/file-opener#21]
Am using the following code:
let pdfOutput = url;
const directory = File.tempDirectory;
File.writeFile(directory, filename, pdfOutput, true).then(success => {
FileOpener.showOpenWithDialog(directory + filename, 'application/pdf')
.then(() => console.log('File opened'))
.catch(e => console.log('Error opening file', e));
},
err => {
console.log(" writing File error : ", err)
})

And am getting the error within XCode when trying to download the file (hosted on firebase) ...

**Comment by ryaa** [comment]
This is correct behavior. The plugin supports only **open** method - see the documentation for details https://github.com/capacitor-community/file-opener#open

**Comment by pmosedale** [comment]
OK, thanks.

So I have revised to:
let pdfOutput = url;
const directory = File.tempDirectory;
File.writeFile(directory, filename, pdfOutput, true).then(success => {
FileOpener.open(filePath(directory + filename), 'application/pdf')
.then(() => console.log('File opened'))
.catch(e => console.log('Error opening file', e));
},
err => {
console.log(" writing File error : ", err)
})

And now nothing happens when attempting to download the file?

**Comment by ryaa** [comment]
> And now nothing happens when attempting to download the file?

The download functionality is not related to this plugin. The problem you are having does not seem to be related to the plugin.
