### ISSUE TITLE
This package should replace pwlin/cordova-plugin-file-opener2

### ISSUE THREAD

**Issue by arnotixe** [capacitor-community/file-opener#22]
The ionic page https://ionicframework.com/docs/native/file-opener points to a repo that has seen no update in 2 years, and the maintainer also has zero activity since December 2021

Therefore capacitor-community/file-opener should replace it on the Ionic pages.

**Comment by ryaa** [comment]
> The ionic page https://ionicframework.com/docs/native/file-opener points to a repo that has seen no update in 2 years, and the maintainer also has zero activity since December 2021
> 
> Therefore capacitor-community/file-opener should replace it on the Ionic pages.

The above link is for the cordova plugins - see https://ionicframework.com/docs/native/community
The correct link for the capacitor community plugins is https://capacitorjs.com/docs/plugins/community and the plugin is listed [here](https://github.com/capacitor-community)

**Comment by arnotixe** [comment]
ok well, the page I linked is an overview page combining both Capacitor, Cordova and Ionic's Enterprise. But I guess the correct place to file an issue is with them, not here :sweat_smile: 

So I'm trying to get in touch with whoever maintains that page instead :+1:
