### ISSUE TITLE
Support Node 14

### ISSUE THREAD

**Issue by BoveFabio** [capacitor-community/file-opener#23]
Hello,
first up, thanks for the great work on this plugin, it's great and works like a charm!

**Is your feature request related to a problem? Please describe.**
We currently cannot move to Node 16 in our work project and need to stay with Node 14. However, that means, we cannot use this plugin. I have tried to use the plugin with Node 14, everything seems to work fine. So, is there a specific reason, why this plugin requires Node >= 16?

**Describe the solution you'd like**
Setting the engines.node field in the package.json to >=14 😊

**Describe alternatives you've considered**
We have obviously considered moving to Node 16 right now. But it's just not possible.

**Additional context**
EDIT: We are using yarn as our package manager. One can still install the dependencies by using `yarn install --ignore-engines`. However, that feels hacky.

Thank you for considering. And if there are specific reasons why Node >=16 is required, please let me know!

**Comment by ryaa** [comment]
> Setting the engines.node field in the package.json to >=14

Ok. I change **engine-strict** to be false in **.npmrc**. This should resolve the problem for you.

> And if there are specific reasons why Node >=16 is required, please let me know!

When building the plugin on node version below 16 it fails with the below error
`Error: Cannot find module 'node:process'`

**Comment by BoveFabio** [comment]
Much appreciated, thank you! When can I roughly expect 1.0.4 to drop?

**Comment by ryaa** [comment]
> Much appreciated, thank you! When can I roughly expect 1.0.4 to drop?

done

**Comment by BoveFabio** [comment]
thank you!
