### ISSUE TITLE
Support for Capacitor v2

### ISSUE THREAD

**Issue by NachoRosatoDim** [capacitor-community/file-opener#27]
Hi there, im having a problem with the plugin fileopener2 and android v12. I found this plugin as a solution but it doesnt support
capacitor v2.

Can you add support for capacitor v2 ? im getting error with register plugin function.

Im like installing any related libraries but cant get anywhere.

Im using ionic capacitor. Thnks for your time and great work :)

**Comment by ryaa** [comment]
This plugin does not support capacitor 2 and there are no plans to support it.
