### ISSUE TITLE
Error Code UNIMPLEMENTED

### ISSUE THREAD

**Issue by infograisonmendoza** [capacitor-community/file-opener#28]
The plugin keeps returnning "FileOpener plugin is not implemented on web" from a real mobile device (Android 10)

1. Install capacitor file openner
2. Import file opener to component
3. Use it :
    fileOpener.open({ filepath: ' ', contentType })

4. Return error on console 
Error: Uncaught (in promise): Error: "FileOpener" plugin is not implemented on web
Error: "FileOpener" plugin is not implemented on web
{
    "__zone_symbol__state": 0,
    "__zone_symbol__value": {
        "code": "UNIMPLEMENTED"
    }
}

**Comment by ryaa** [comment]
@infograisonmendoza I can not reproduce this problem. Can you please create a repository in the GitHub with the sample app demonstrating the problem?

**Comment by ryaa** [comment]
The problem can not be reproduced. Closing

**Comment by desarrollo3-diapli** [comment]
I have the same problem.

Using this code:
  ```
FileOpener.open({ filePath: this.rutasDoc[index].download, contentType: 'application/pdf'})
      .then(() => {
      })
      .catch(e => console.log('Error opening file...', e));
```

I get this error:
![Captura de pantalla 2023-02-21 a las 13 49 13](https://user-images.githubusercontent.com/85868292/220349435-1e3d997f-7a88-40e7-9a8f-db199afb079b.png)

**Comment by ryaa** [comment]
@desarrollo3-diapli I can not reproduce this problem. Can you please create a repository in the GitHub with the sample app demonstrating the problem?

**Comment by muuvmuuv** [comment]
Maybe you forgot to `cap sync`? This message only comes if it is not implemented OR if you forgot to sync/update the native dependencies which will register them as a native plugin.

**Comment by ryaa** [comment]
The problem can not be reproduced. Closing

**Comment by NikosChou** [comment]
Hi, I had the same problem in ios. I managed to fix it following the instructions in https://capacitorjs.com/docs/ios/troubleshooting#plugin-not-implemented (removing the WKAppBoundDomains from Info.plist)
