### ISSUE TITLE
Downloaded PDF files cannot be opened under iOS

### ISSUE THREAD

**Issue by Timbuktu1982** [capacitor-community/file-opener#30]
Hi there,
i have fetched a pdf and save it into download folder. But when i open this downloaded file in iOS, it is not working. The file size and the content inside the file are correct. In Android it works. But not in iOS. What went wrong in iOS? Or what i can do to fix this problem?
Thx

**Comment by Timbuktu1982** [comment]
Sorry, i forgot to describe the problem: In iOS the file is opened, but has only a white screen...

**Comment by Timbuktu1982** [comment]
When i open this file with AdobeAcrobatReader, than all is correct. But not all users have installed the AdobeAcrobatReader...

**Comment by ryaa** [comment]
@Timbuktu1982 can you please send me the pdf file that causes that problem? What is the iOS version where the problem exists? Do you have the required app installed on iOS device which can open this file there?

**Comment by Timbuktu1982** [comment]
Hi ryaa,
thank you for your response.
Last weekend I searched intensively for a cause for this problem and found a lot of information, but no solution.
I have read about problems with content-security-policy headers for sandbox, but thats not the solution.
In other cases, I see that Apple has changed many things for pdfs since Mac OS BigSure and similarly in the mobile versions since iOS13.

In my case i have PDFs they works perfectly (i see the version of Adobe 1.5 in the document properties of this) and i have PDFs they works only not in safari, but in all other browsers (here i see the version of Adobe 1.6 in the document properties of this).

Here is a document they will not work in Safari:
https://p488859.mittwaldserver.info/public/anatomy.pdf

This is a very difficult problem for me, as I cannot identify the cause....

**Comment by Timbuktu1982** [comment]
Sorry, here the informaiton about version:
On my Mac i use MacOS Ventura 13.01.
On my phone i have installed iOS15.
On xcode simulators i tested all versions since iOS13.

**Comment by ryaa** [comment]
The problem is not with the file opener plugin but with the default pdf viewer on iOS devices. If you open you pdf file in safari it will show the white screen. The same will happen if your the pdf file opened using this plugin which opens it in the default pdf view if the plugin **openWithDefault** option is set to true.
To be able to open your pdf file on iOS please make sure to install some pdf viewer (for example, Adobe PDF reader) on your iOS device and use **openWithDefault** set to false when opening the pdf file. It will present a menu restricted to a list of apps capable of opening the current document. From this list, choose Adobe PDF viewer and your file will show just fine.

For details about **openWithDefault** option please see https://github.com/capacitor-community/file-opener#fileopeneroptions

**Comment by Timbuktu1982** [comment]
Hi ryaa,
thank you for your help in this case. I have considered this solution, but it is absolutely impractical. 
Why?
Not all users have Adobe Acrobat Reader on their device and do not want to install it.

That's not the problem of file-opener in general, i know (see my posts before). But apple said, you must send specific http-headers to browser to open affected pdf (this is where file-opener plays a role) . I have tested a number of headers (direct call of the pdf file concerned) as described by Apple. But there is no improvement.

Have you an another idea to fix the problem?

**Comment by ryaa** [comment]
That's not the problem of file-opener in general, i know (see my posts before). But apple said, you must send specific http-headers to browser to open affected pdf (this is where file-opener plays a role) 
>

When I open your pdf on my mac book machine in the safari browser it is also white screen, therefore I assume that this is not file opener problem.

> Have you an another idea to fix the problem?

Create pdf file that can be opened correctly in the default iOS pdf viewer/safari.

**Comment by Timbuktu1982** [comment]
> When I open your pdf on my mac book machine in the safari browser it is also white screen, therefore I assume that this is not file opener problem.

I realise that the FileOpener cannot do anything about this. However, if HTTP headers would help, the FileOpener would have to pass them to the browser (this is how Apple described it). 

> Create pdf file that can be opened correctly in the default iOS pdf viewer/safari.

I have long considered this idea, but these countless PDFs are no longer available in a convertible form, but only in the form of the finished PDF files.

**Comment by ryaa** [comment]
I believe that this is the problem with PDF file format and this is not the file opener plugin issue. If you want to customize the plugin behavior, please feel free to fork and make the required changes. thank you

**Comment by nguyenlamlll** [comment]
I know it has been a while but I experienced somewhat the same thing. 

In my case, I upload my PDF files to Azure Blob storage. By default, the uploaded files have the Content-type of "application/octet-stream". In my app on iOS, the plugin cannot open the file preview. When I debug on xCode, it gives the error code 8, which means "FILE_NOT_SUPPORTED". 

After I update the Content type on Azure Blob storage to **"application/pdf"**, after downloading, this plugin can open the file instantly.

I don't know how you serve your PDF files, but I guess it does not necessarily means your PDF formats are wrong. Maybe an HTTP header from your web server's response may help?
