### ISSUE TITLE
Capacitor 5 support

### ISSUE THREAD

**Issue by AE1NS** [capacitor-community/file-opener#36]
Migration guide: https://capacitorjs.com/docs/next/updating/plugins/5-0

PR: https://github.com/capacitor-community/file-opener/pull/35

**Comment by ryaa** [comment]
The plugin version 1.0.5 now supports capacitor version 3.x, 4.x and 5.x - see https://github.com/capacitor-community/file-opener/blob/chore/release-1.0.5/CHANGELOG.md
