### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by leas251** [capacitor-community/file-opener#39]
**Describe the bug**
Hi, I'm working with Capacitor and Angular for different Platforms. File-opener works fine on iOS and Android. It's also possible to run the app on Mac OS (Apple introduced the possibility this year if I'm correct). And on Mac OS I get this error:

To Native ->  FileOpener open 72181771
ERROR MESSAGE:  {"message":"Failed to open the file preview","code":"8","errorMessage":"Failed to open the file preview"}
⚡️  [error] - {"message":"Failed to open the file preview","code":"8","errorMessage":"Failed to open the file preview"}
⚡️  [log] - Error opening file {"code":"8","errorMessage":"Failed to open the file preview"}

It runs fine on iPads and iPhones.

**To Reproduce**
1. Save a File locally:
  ```
async saveFile(base64Data, sheet: Sheet) {
    await Filesystem.writeFile({
      path: `${environment.sheetsCacheFolder}/${sheet.path}`,
      data: base64Data,
      directory: Directory.Cache
    });

    Filesystem.readFile({
      directory: Directory.Cache,
      path: `${environment.sheetsCacheFolder}/${sheet.path}`
    }).then(async file => {
      const uri = (await Filesystem.getUri({path: `${environment.sheetsCacheFolder}/${sheet.path}`, directory: Directory.Cache})).uri;
      this.openFile(file.data, uri);
    });
  }
```

2. Try to open it with File-opener:
  ```
async openFile(data, path: string) {
    const mimeType = 'application/pdf';

    FileOpener.open({ filePath: path, contentType: mimeType})
      .catch(error => console.log('Error opening file', error));
  }
```

**Expected behavior**
On Mobile devices (including running on simulators) it should work fine. When running it on a Mac OS device (MacBook or similar) get this error:
⚡️  To Native ->  FileOpener open 33017550
ERROR MESSAGE:  {"message":"Failed to open the file preview","errorMessage":"Failed to open the file preview","code":"8"}
⚡️  [error] - {"message":"Failed to open the file preview","errorMessage":"Failed to open the file preview","code":"8"}
⚡️  [log] - Error opening file {"code":"8","errorMessage":"Failed to open the file preview"}

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.3.1
 - Version 1.0.5

**Comment by leas251** [comment]
I found a way around: If I don't use the "openWithDefault" option it's working on Mac OS.

So I did this little tweak in the plugin code which is not the best solution but it helps at the moment:
```
            if (openWithDefault) {
                wasOpened = self.documentInteractionController.presentPreview(animated: true)
            }
            
            if ((openWithDefault && !wasOpened) || !openWithDefault ) {

```

**Comment by ryaa** [comment]
The plugin is supported on iOS and Android only. I have never tested and there are no plans to support it on MacOS right now.
