### ISSUE TITLE
When will the package be released?

### ISSUE THREAD

**Issue by FreekMencke** [capacitor-community/file-opener#4]
**Describe the bug**
This package is what I have been looking for. When I tried installing it, I noticed that it has not been released yet.

Any idea when this plugin will be released?

**To Reproduce**
1. `npm install @capacitor-community/file-opener` 

**Expected behavior**
Download en install the package

**Comment by ryaa** [comment]
> Any idea when this plugin will be released?

as soon as i will be granted the permission to publish the npm package to capacitor-community. it seems that there is no straightforward workflow to do this and I have to request this permission through slack channel and not sure when it will be approved :(

For now, you can install the plugin using the below command:
`npm install capacitor-community/file-opener#chore/latest-version-with-dist-directory`

Let me know if you can install the plugin using the above command and if it works as expected. thank you

**Comment by ryaa** [comment]
The package has been released - see https://www.npmjs.com/package/@capacitor-community/file-opener
