### ISSUE TITLE
Version 1.0.4 JAVA VERSION 17

### ISSUE THREAD

**Issue by massimoliani** [capacitor-community/file-opener#43]
I'm using file opener on Capacitor 4 in two different apps.
One apps installed some moth ago with file opener 1.0.4 is working fine.

A new one installed today, version 1.0.4 as net version is for Capacitor 5 has a bug inside.

Inside node_modules android src the build gradle report JavaVersion.VERSION_17 that is incompatible with Capacitor 4 JavaVersion.VERSION_11.

I modify the node modules build gradle to VERSION_11 and everything work fine.

Running from Mac OS, npm install

Capacitor 4.

**Comment by ryaa** [comment]
Plugin version 1.0.4 is compatible with Capacitor 4. For Capacitor 5 please use the plugin version 1.0.5

Please also see https://github.com/capacitor-community/file-opener/issues/41#issuecomment-1559059650
