### ISSUE TITLE
Do not use a npm prepare script

### ISSUE THREAD

**Issue by pct-cclausen** [capacitor-community/file-opener#48]
In our workspace using NX with @nxext/capacitor we have a somewhat special (?) situation where everything works great, except it turns out that if a capacitor plugins defines a prepare step in its npm scripts, @nxext/capacitor:cap sync causes that prepare step to trigger.

For this library it means the dist folder of file-opener in node_modules is deleted, breaking the lib.

See here for more details: https://github.com/nxext/nx-extensions-ionic/issues/4

It turns out that for the last 15 capacitor plugins we have not had any problems, as none of them use a prepare step, and our setup works great.

file-opener however uses a prepare step. Maybe it's build process could somehow be modified in a small way to not use it?

**Comment by ryaa** [comment]
I have removed `prepare` script from _package.json_ (see https://github.com/capacitor-community/file-opener/pull/50). Let me know if this fixes your issue. Thank you

**Comment by pct-cclausen** [comment]
thanks, this helps :)
