### ISSUE TITLE
Example required

### ISSUE THREAD

**Issue by flyon** [capacitor-community/file-opener#51]
Its not clear to me how to use this and what it can be used for. Is it only for files of the internal file system? Or can I use this to open files from the web?

Im looking for a way to download and open a PDF from the web. Can I use this plugin? In combination perhaps with the capacitor file system plugin to download the file to a local path?

For a new person coming to this repo it's currently not clear how & for what this plugin can be used.  An example would be helpful

**Comment by ryaa** [comment]
I personally use this plugin in my capacitor based mobile app to open the local/downloaded files. Once the file is downloaded and saved to the internal application storage, the plugin open (see https://github.com/capacitor-community/file-opener?tab=readme-ov-file#api) method is invoked with the appropriate arguments.

I hope that this information is useful.
