### ISSUE TITLE
support capacitor v6.0.0

### ISSUE THREAD

**Issue by moh4sa** [capacitor-community/file-opener#54]
**Is your feature request related to a problem? Please describe.**
current version of the this plugin doesn't support capacitor v6.0.0
While resolving: @capacitor-community/file-opener@1.0.6
npm ERR! Found: @capacitor/core@6.0.0
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^6.0.0" from @capacitor/android@6.0.0
npm ERR!   node_modules/@capacitor/android
npm ERR!     @capacitor/android@"^6.0.0" from the root project
npm ERR!   peer @capacitor/core@"^6.0.0" from @capacitor/app@6.0.0
npm ERR!   node_modules/@capacitor/app
npm ERR!     @capacitor/app@"^6.0.0" from the root project
npm ERR!   10 more (@capacitor/browser, @capacitor/haptics, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^5.0.0" from @capacitor-community/file-opener@1.0.6
npm ERR! node_modules/@capacitor-community/file-opener
npm ERR!   @capacitor-community/file-opener@"^1.0.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @capacitor/core@5.7.5
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^5.0.0" from @capacitor-community/file-opener@1.0.6
npm ERR!   node_modules/@capacitor-community/file-opener
npm ERR!     @capacitor-community/file-opener@"^1.0.5" from the root project

**Describe the solution you'd like**
add support to capacitor v6.0.0

**Comment by ryaa** [comment]
New build v6.0.0 has been released. For more details please see CHANGELOG

@moh4sa thank you for the contribution
