### ISSUE TITLE
Troubleshooting section not present

### ISSUE THREAD

**Issue by JulienLecoq** [capacitor-community/file-opener#57]
**Describe the bug**
This section is shown in the table of content but does not exist: [Troubleshooting](https://github.com/capacitor-community/file-opener/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#troubleshooting)

**Expected behavior**
The section should not be shown in the table of content if it does not exist.

**Comment by ryaa** [comment]
Thank you for reporting this issue. I have removed Troubleshooting header.
