### ISSUE TITLE
Node engine restriction, but why?

### ISSUE THREAD

**Issue by de-dan** [capacitor-community/file-opener#6]
Hi. Is there a specific reason why the node engine is restricted?
I'm using node 18 and it is working fine, but the warning bugs me :)

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@capacitor-community/file-opener@1.0.1',
npm WARN EBADENGINE   required: { node: '>=16.15.0 <17.0', npm: '>=8.10.0 <9.0' },
npm WARN EBADENGINE   current: { node: 'v18.7.0', npm: '8.15.0' }
npm WARN EBADENGINE }

**Comment by ryaa** [comment]
I tested with the above node and npm combinations and will support any issues with these specific version. Other versions may work but i can not guarantee supporting all the possible node/npm versions.
We can relax the node version to include 18.x if this works fine. Can you please create a PR? :) thank you

**Comment by de-dan** [comment]
Hi @ryaa, thanks for your quick response. I raised a PR. I'm still not convinced that this is the best approach, as the restriction should come from the underlying framework (Capacitor) and this plugin should (automatically) support the same versions. But that is just my opinion :) Thanks for your work

**Comment by ryaa** [comment]
> as the restriction should come from the underlying framework (Capacitor) and this plugin should (automatically) support the same versions.

make sense. thank you for the contribution.
