### ISSUE TITLE
Questions: can data URI or app internal web-server be used (on iOS)?

### ISSUE THREAD

**Issue by bluepuma77** [capacitor-community/file-opener#60]
The doc states:
> The plugin is able to open a file given the mimeType and the file uri.

About this I have 2 questions:
1. Can file-opener use a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme)* and open a PDF in a native viewer?
2. Can CapacitorJS start it's own "localhost web server" (like [capacitor-file-chunk](https://github.com/qrclip/capacitor-file-chunk)) and the native viewer can load a PDF from it?

\* Example data URI of minimal PDF ([source](https://stackoverflow.com/questions/17279712/what-is-the-smallest-possible-valid-pdf)):
```
data:application/pdf;base64,JVBERi0xLjEKJcKlwrHDqwoKMSAwIG9iagogIDw8IC9UeXBlIC9DYXRhbG9nCiAgICAgL1BhZ2VzIDIgMCBSCiAgPj4KZW5kb2JqCgoyIDAgb2JqCiAgPDwgL1R5cGUgL1BhZ2VzCiAgICAgL0tpZHMgWzMgMCBSXQogICAgIC9Db3VudCAxCiAgICAgL01lZGlhQm94IFswIDAgMzAwIDE0NF0KICA+PgplbmRvYmoKCjMgMCBvYmoKICA8PCAgL1R5cGUgL1BhZ2UKICAgICAgL1BhcmVudCAyIDAgUgogICAgICAvUmVzb3VyY2VzCiAgICAgICA8PCAvRm9udAogICAgICAgICAgIDw8IC9GMQogICAgICAgICAgICAgICA8PCAvVHlwZSAvRm9udAogICAgICAgICAgICAgICAgICAvU3VidHlwZSAvVHlwZTEKICAgICAgICAgICAgICAgICAgL0Jhc2VGb250IC9UaW1lcy1Sb21hbgogICAgICAgICAgICAgICA+PgogICAgICAgICAgID4+CiAgICAgICA+PgogICAgICAvQ29udGVudHMgNCAwIFIKICA+PgplbmRvYmoKCjQgMCBvYmoKICA8PCAvTGVuZ3RoIDU1ID4+CnN0cmVhbQogIEJUCiAgICAvRjEgMTggVGYKICAgIDAgMCBUZAogICAgKEhlbGxvIFdvcmxkKSBUagogIEVUCmVuZHN0cmVhbQplbmRvYmoKCnhyZWYKMCA1CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxOCAwMDAwMCBuIAowMDAwMDAwMDc3IDAwMDAwIG4gCjAwMDAwMDAxNzggMDAwMDAgbiAKMDAwMDAwMDQ1NyAwMDAwMCBuIAp0cmFpbGVyCiAgPDwgIC9Sb290IDEgMCBSCiAgICAgIC9TaXplIDUKICA+PgpzdGFydHhyZWYKNTY1CiUlRU9GCg==
```

**Comment by ryaa** [comment]
@bluepuma77 I'm not sure I can answer the above questions without additional research. It would be helpful if you can try and let everyone know your findings :) thank you

**Comment by ryaa** [comment]
No feedback received so closing this ticket.
