### ISSUE TITLE
Add "sheet" mode 

### ISSUE THREAD

**Issue by fanckush** [capacitor-community/file-opener#65]
It would be so good if it were possible to open the file as a sheet instead of the current full-screen mode

something like

```ts
    const fileOpenerOptions: FileOpenerOptions = {
      filePath: 'file://some/path',
      contentType: 'application/pdf',
      mode: 'sheet' // | 'fullscreen'
    }

    await FileOpener.open(fileOpenerOptions)
```

is this even possible?

**Comment by ryaa** [comment]
> is this even possible?

Currently the plugin delegates opening a file to a native app which support this file format. To open the file as a sheet, as I see, the plugin will have to support displaying it itself. This should be doable for some formats (for, example images/video etc.) but might be tricky for others. I would say, that this is going to be a considerable effort to support this feature and not planning to implement it.
