### ISSUE TITLE
Verification isSupported on iOS

### ISSUE THREAD

**Issue by luisgaliciadev** [capacitor-community/file-opener#68]
Problem Description
The isSupported() method returns false on iOS 16 with iPhone 16 Pro Max, even when NFC is enabled.

Steps to Reproduce
Set up the plugin @capawesome-team/capacitor-nfc in an Ionic project using Capacitor.
Implement the Nfc.isSupported() method.
Run the application on an iPhone 16 Pro Max with iOS 16.
The method returns false.
Expected Behavior
The isSupported() method should return true if the device supports NFC.

Actual Behavior
The isSupported() method always returns false, even though the device supports NFC.

Environment
- Device: iPhone 16 Pro Max
- Plugin: @capawesome-team/capacitor-nfc v6.5.0
- @capacitor/core: v6.2.0

**Comment by ryaa** [comment]
This issue seems to be for `@capawesome-team/capacitor-nfc` plugin and not related to `@capacitor-community/file-opener`
